#ifndef _ERRCODES_H
#define _ERRCODES_H

#define RC_ERR_GENERAL_ERROR			    1
#define RC_ERR_CHROME_MESSAGE_TO_LARGE		7001
#define RC_ERR_CHROME_FAILED_MESSAGE		7002
#define RC_ERR_JSON_FAIL_READ_MSG		    7003
#define RC_ERR_JSON_MISS_REQFIELD		    7004
#define RC_ERR_INVALID_MSGFORMAT		    7005
#define RC_ERR_COULDNOT_PARSEJSON		    7006
#define RC_ERR_FAILED_TO_LAUNCHJVM		    7007
#define RC_ERR_FAILED_FIND_APPCLLOADER	    7008
#define RC_ERR_FAILED_CRE_APPCLLOADER	    7009
#define RC_ERR_FAILED_FIND_APPCLLOADMETHOD  7010
#define RC_ERR_NO_JVMPROCESS_AVAIL          7011
#define RC_ERR_FAILED_CREATE_PARAM_ARRAY    7012
#define RC_ERR_BUFFER_SZ_TOOSMALL           7013
#define RC_ERR_POLICY_FILE_MISSING          7014
#define RC_ERR_MISSING_OPLAUCH_ENVVAR       7015
#define RC_ERR_FILE_LOADSYSLIBS             7016

#endif //_ERRCODES_H
