#ifndef _ERRCODES_H
#define _ERRCODES_H

#define RC_ERR_GENERAL_ERROR			    1
#define RC_ERR_CHROME_MESSAGE_TO_LARGE		7001
#define RC_ERR_CHROME_FAILED_MESSAGE		7002
#define RC_ERR_JSON_FAIL_READ_MSG		    7003
#define RC_ERR_JSON_MISS_REQFIELD		    7004
#define RC_ERR_INVALID_MSGFORMAT		    7005
#define RC_ERR_COULDNOT_PARSEJSON		    7006
#define RC_ERR_FAILED_TO_LAUNCHJVM		    7007
#define RC_ERR_FAILED_FIND_APPCLLOADER	    7008
#define RC_ERR_FAILED_CRE_APPCLLOADER	    7009
#define RC_ERR_FAILED_FIND_APPCLLOADMETHOD  7010
#define RC_ERR_NO_JVMPROCESS_AVAIL          7011
#define RC_ERR_FAILED_CREATE_PARAM_ARRAY    7012
#define RC_ERR_BUFFER_SZ_TOOSMALL           7013
#define RC_ERR_POLICY_FILE_MISSING          7014
#define RC_ERR_MISSING_OPLAUCH_ENVVAR       7015
#define RC_ERR_FILE_LOADSYSLIBS             7016
#define RC_ERR_JVMNOTLOADED                 7017
#define RC_ERR_FAILEDJVM_ATTACH             7018
#define RC_ERR_CLLOADER_METHOD_NOTFOUND     7019
#define RC_ERR_CANNOT_CLASS_INSTANCE        7020
#define RC_ERR_WRONG_RESULT_CLLOADER        7021
#define RC_ERR_TYPECONVERTING_FAILED        7022
#define RC_ERR_FAILED_B64_BUFFERSZ          7023
#define RC_ERR_MEMORY_ALLOCATION_FAILED     7024
#define RC_ERR_ENCDEC_B64                   7025
#define RC_ERR_IO_FILEOPEN_FAILED           7026
#define RC_ERR_IO_READWRITE_FAILED          7027
#define RC_ERR_IO_CREATEDIR_FAILED          7028
#define RC_ERR_MSIO_RETRIEVAL_FAILED        7029
#define RC_ERR_MISSING_ENV_VARIABLE         7030
#define RC_ERR_IO_FILENOTFOUND              7031
#define RC_ERR_INVALID_PARAMETER            7032
#define RC_ERR_INVALID_PATH                 7033
#define RC_ERR_NOT_INITIALIZED              7034
#define RC_ERR_IO_OPEN_FAILED               7035
#define RC_WARN_OPCODE_NOT_SUPPORTED        7036
#define RC_ERR_FAILED_LOAD_APPLET           7037
#define RC_ERR_FAILED_CREATE_THREAD         7038
#define RC_ERR_FAILED_WSL_LOAD              7039
#define RC_ERR_TCPIP_FAILED                 7040
#define RC_ERR_TCPIP_CLIENT_CONNECTED       7041
#define RC_ERR_CREATEUPT_REGKEY             7042
#define RC_ERR_READ_READ_REGVAL             7043
#define RC_ERR_SECUR_GENRAND_DES3_KEY       7044
#define RC_ERR_SECUR_FAILED_DES3_DECRYPT    7045
#define RC_ERR_SECUR_FAILED_DES3_ENCRYPT    7046
#define RC_ERR_CHROME_WRONG_PAYLOAD         7047
#define RC_ERR_DECODE_MSG_ERROR             7048
#define RC_ERR_MEMORY_ALLOCATION            7049

#endif //_ERRCODES_H
