package org.oplauncher;

public enum ErrorCode {
    GENERAL_ERROR(8000),
    UNSUPPORTED_OPERATION(8001),
    MALFORMED_URL(8002),
    SECURITY_ERROR(8003),
    FAILED_TO_DOWNLOAD_FILE(8004),
    UNSUPPORTED_OPCODE(8005),
    CLASSPATH_LOAD_ERROR(8006),
    UNSUPPORTED_APPLET_CONTEXT(8007),
    APPLET_EXECUTION_ERROR(8008),
    UNSUPPORTED_ARCHIVE_CLZLOADER(8009),
    FAILED_TO_LOAD_RESOURCE(8010),
    NO_VALID_CHROME_TOKEN_FOUND(8011),
    OPSERVER_NOT_AVAILABLE(8012),
    ERROR_LISTENING_OPSERVER(8013),
    JSON_PROTOCOL_ERROR(8014),
    EMPTY_JSON_PAYLOAD(8015),
    APPTKN_AUTH_ERROR(8016),
    NO_VALID_APP_TOKEN(8017),
    DISPATCHER_GENERAL_ERROR(8018),
    DISPATCHER_MISSING(8019),
    ERROR_SECURITY_ERROR(8020),
    UNSUPPORTED_CIPHER_TYPE(8021),
    FAILED_VALID_MAGIC_NUMBER(8022),
    SECURE_PAYLOAD_PARSE_ERROR(8023),
    REFLECTION_ERROR(8024)
      ;

    private ErrorCode(int cd) {
        _code = cd;
    }

    public int code() { return _code; }
    // class properties
    private int _code;
}
